language: python
sudo: required
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
script: make test-coveralls
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE pgcrypto_fields' -U postgres
  - psql -c 'CREATE DATABASE pgcrypto_fields_diff' -U postgres
  - psql -c 'select * from pg_available_extensions' -U postgres
install:
  - pip install -e .
  - pip install -r requirements_dev.txt
  - pip install $DJANGO
env:
  matrix:
    - DJANGO='django>=2.2,<2.3'
    - DJANGO='django>=3.0,<3.1'
    - DJANGO='django>=3.1,<3.2'
    - DJANGO='django>=3.2,<3.3'
    - DJANGO='django==3.2.0'
    - DJANGO='--upgrade --pre django'
matrix:
  fast_finish: true
  allow_failures:
    - env: DJANGO='--upgrade --pre django'
    - python: 3.9-dev
